/// <reference types="cypress" />

describe("User Flow: As a user, I should be able to view a list of all the available newspaper sections at the top of the page", () => {

  beforeEach(() => {
    cy.intercept("GET", "https://api.nytimes.com/svc/topstories/v2/arts.json?api-key=${apiKey}", {fixture: "../fixtures/arts-articles.json"})
    cy.visit('http://localhost:5173/'); 
  });

  it("Should show a navigation bar at the top with links to sections", () => {
    cy.get("nav").should("have.class", "newsPaperSections")
  });
  
  it("The navigation bar should have working links to each section of the newspaper", () => {
    cy.get('[href="/arts"]').contains("ARTS").click().url().should("eq", "http://localhost:5173/arts") 
    cy.intercept("GET", "https://api.nytimes.com/svc/topstories/v2/arts.json?api-key=${apiKey}", {fixture: "../fixtures/arts-articles.json"}) 
    cy.go("back")
    cy.wait(2000)
    cy.get('[href="/automobiles"]').contains("AUTOMOBILES").click().url().should("eq", "http://localhost:5173/automobiles") 
    cy.intercept("GET", "https://api.nytimes.com/svc/topstories/v2/automobiles.json?api-key=${apiKey}", {fixture: "../fixtures/arts-articles.json"}) 
    cy.go("back")
    cy.wait(2000)
    cy.get('[href="/books"]').contains("BOOKS").click().url().should("eq", "http://localhost:5173/books") 
    cy.intercept("GET", "https://api.nytimes.com/svc/topstories/v2/books.json?api-key=${apiKey}", {fixture: "../fixtures/arts-articles.json"}) 
    cy.go("back")
    cy.wait(2000)
    cy.get('[href="/business"]').contains("BUSINESS").click().url().should("eq", "http://localhost:5173/business") 
    cy.intercept("GET", "https://api.nytimes.com/svc/topstories/v2/business.json?api-key=${apiKey}", {fixture: "../fixtures/arts-articles.json"})  
    cy.go("back")
    cy.wait(2000)
    cy.get('[href="/fashion"]').contains("FASHION").click().url().should("eq", "http://localhost:5173/fashion") 
    cy.intercept("GET", "https://api.nytimes.com/svc/topstories/v2/fashion.json?api-key=${apiKey}", {fixture: "../fixtures/arts-articles.json"}) 
    cy.go("back")
    cy.wait(2000)
    cy.get('[href="/food"]').contains("FOOD").click().url().should("eq", "http://localhost:5173/food") 
    cy.intercept("GET", "https://api.nytimes.com/svc/topstories/v2/food.json?api-key=${apiKey}", {fixture: "../fixtures/arts-articles.json"}) 
    cy.go("back")
    cy.wait(2000)
    cy.get('[href="/health"]').contains("HEALTH").click().url().should("eq", "http://localhost:5173/health") 
    cy.intercept("GET", "https://api.nytimes.com/svc/topstories/v2/health.json?api-key=${apiKey}", {fixture: "../fixtures/arts-articles.json"}) 
    cy.go("back")
    cy.wait(2000)
    cy.get('[href="/insider"]').contains("INSIDER").click().url().should("eq", "http://localhost:5173/insider") 
    cy.intercept("GET", "https://api.nytimes.com/svc/topstories/v2/insider.json?api-key=${apiKey}", {fixture: "../fixtures/arts-articles.json"}) 
    cy.go("back")
    cy.wait(2000)
    cy.get('[href="/magazine"]').contains("MAGAZINE").click().url().should("eq", "http://localhost:5173/magazine") 
    cy.intercept("GET", "https://api.nytimes.com/svc/topstories/v2/magazine.json?api-key=${apiKey}", {fixture: "../fixtures/arts-articles.json"}) 
    cy.go("back")
    cy.wait(2000)
    cy.get('[href="/movies"]').contains("MOVIES").click().url().should("eq", "http://localhost:5173/movies") 
    cy.intercept("GET", "https://api.nytimes.com/svc/topstories/v2/movies.json?api-key=${apiKey}", {fixture: "../fixtures/arts-articles.json"}) 
    cy.go("back")
    cy.wait(2000)
    cy.get('[href="/nyregion"]').contains("NYREGION").click().url().should("eq", "http://localhost:5173/nyregion") 
    cy.intercept("GET", "https://api.nytimes.com/svc/topstories/v2/nyregion.json?api-key=${apiKey}", {fixture: "../fixtures/arts-articles.json"}) 
    cy.go("back")
    cy.wait(2000)
    cy.get('[href="/obituaries"]').contains("OBITUARIES").click().url().should("eq", "http://localhost:5173/obituaries") 
    cy.intercept("GET", "https://api.nytimes.com/svc/topstories/v2/obituaries.json?api-key=${apiKey}", {fixture: "../fixtures/arts-articles.json"}) 
    cy.go("back")
    cy.wait(2000)
    cy.get('[href="/opinion"]').contains("OPINION").click().url().should("eq", "http://localhost:5173/opinion") 
    cy.intercept("GET", "https://api.nytimes.com/svc/topstories/v2/opinion.json?api-key=${apiKey}", {fixture: "../fixtures/arts-articles.json"}) 
    cy.go("back")
    cy.wait(2000)
    cy.get('[href="/politics"]').contains("POLITICS").click().url().should("eq", "http://localhost:5173/politics") 
    cy.intercept("GET", "https://api.nytimes.com/svc/topstories/v2/politics.json?api-key=${apiKey}", {fixture: "../fixtures/arts-articles.json"}) 
    cy.go("back")
    cy.wait(2000)
    cy.get('[href="/realestate"]').contains("REALESTATE").click().url().should("eq", "http://localhost:5173/realestate") 
    cy.intercept("GET", "https://api.nytimes.com/svc/topstories/v2/realestate.json?api-key=${apiKey}", {fixture: "../fixtures/arts-articles.json"}) 
    cy.go("back")
    cy.wait(2000)
    cy.get('[href="/science"]').contains("SCIENCE").click().url().should("eq", "http://localhost:5173/science") 
    cy.intercept("GET", "https://api.nytimes.com/svc/topstories/v2/science.json?api-key=${apiKey}", {fixture: "../fixtures/arts-articles.json"}) 
    cy.go("back")
    cy.wait(2000)
    cy.get('[href="/sundayreview"]').contains("SUNDAYREVIEW").click().url().should("eq", "http://localhost:5173/sundayreview") 
    cy.intercept("GET", "https://api.nytimes.com/svc/topstories/v2/sundayreview.json?api-key=${apiKey}", {fixture: "../fixtures/arts-articles.json"}) 
    cy.go("back")
    cy.wait(2000)
    cy.get('[href="/technology"]').contains("TECHNOLOGY").click().url().should("eq", "http://localhost:5173/technology") 
    cy.intercept("GET", "https://api.nytimes.com/svc/topstories/v2/technology.json?api-key=${apiKey}", {fixture: "../fixtures/arts-articles.json"}) 
    cy.go("back")
    cy.wait(2000)
    cy.get('[href="/theater"]').contains("THEATER").click().url().should("eq", "http://localhost:5173/theater") 
    cy.intercept("GET", "https://api.nytimes.com/svc/topstories/v2/theater.json?api-key=${apiKey}", {fixture: "../fixtures/arts-articles.json"}) 
    cy.go("back")
    cy.wait(2000)
    cy.get('[href="/t-magazine"]').contains("T-MAGAZINE").click().url().should("eq", "http://localhost:5173/t-magazine") 
    cy.intercept("GET", "https://api.nytimes.com/svc/topstories/v2/t-magazine.json?api-key=${apiKey}", {fixture: "../fixtures/arts-articles.json"}) 
    cy.go("back")
    cy.wait(2000)
    cy.get('[href="/travel"]').contains("TRAVEL").click().url().should("eq", "http://localhost:5173/travel") 
    cy.intercept("GET", "https://api.nytimes.com/svc/topstories/v2/travel.json?api-key=${apiKey}", {fixture: "../fixtures/arts-articles.json"}) 
    cy.go("back")
    cy.wait(2000)
    cy.get('[href="/upshot"]').contains("UPSHOT").click().url().should("eq", "http://localhost:5173/upshot") 
    cy.intercept("GET", "https://api.nytimes.com/svc/topstories/v2/upshot.json?api-key=${apiKey}", {fixture: "../fixtures/arts-articles.json"}) 
    cy.go("back")
    cy.wait(2000)
    cy.get('[href="/sports"]').contains("SPORTS").click().url().should("eq", "http://localhost:5173/sports") 
    cy.intercept("GET", "https://api.nytimes.com/svc/topstories/v2/sports.json?api-key=${apiKey}", {fixture: "../fixtures/arts-articles.json"}) 
    cy.go("back")
    cy.wait(2000)
    cy.get('[href="/us"]').contains("US").click().url().should("eq", "http://localhost:5173/us") 
    cy.intercept("GET", "https://api.nytimes.com/svc/topstories/v2/us.json?api-key=${apiKey}", {fixture: "../fixtures/arts-articles.json"}) 
    cy.go("back")
    cy.wait(2000)
    cy.get('[href="/world"]').contains("WORLD").click().url().should("eq", "http://localhost:5173/world") 
    cy.intercept("GET", "https://api.nytimes.com/svc/topstories/v2/world.json?api-key=${apiKey}", {fixture: "../fixtures/arts-articles.json"}) 
    cy.go("back")
  });
})
